CREATE TABLE category
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    parent_id BIGINT,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE expense
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    amount       DOUBLE PRECISION                        NOT NULL,
    comment      VARCHAR(255)                            NULL,
    is_mandatory BOOLEAN                                 NOT NULL,
    category_id  BIGINT                                  NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    timestamp    TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_expense PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date      TIMESTAMP WITH TIME ZONE                NOT NULL,
    modified_date     TIMESTAMP WITH TIME ZONE                NOT NULL,
    telegram_user_id  BIGINT,
    telegram_username VARCHAR(255),
    language_code     VARCHAR(255),
    first_name        VARCHAR(255),
    last_name         VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_category
(
    category_id BIGINT NOT NULL,
    user_id     BIGINT NOT NULL
);

ALTER TABLE category
    ADD CONSTRAINT FK_CATEGORY_ON_PARENT FOREIGN KEY (parent_id) REFERENCES category (id);

ALTER TABLE expense
    ADD CONSTRAINT FK_EXPENSE_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id),
    ADD CONSTRAINT FK_EXPENSE_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE user_category
    ADD CONSTRAINT fk_usecat_on_category FOREIGN KEY (category_id) REFERENCES category (id),
    ADD CONSTRAINT fk_usecat_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);
