package com.basnukaev.finance.app.telegram.handler

object CallbackQueryValue {
    const val USER_CHOSEN_IS_MANDATORY = "USER_CHOSEN_IS_MANDATORY"
    const val USER_CHOSEN_IS_MANDATORY_YES = "USER_CHOSEN_IS_MANDATORY?answer=YES"
    const val USER_CHOSEN_IS_MANDATORY_NO = "USER_CHOSEN_IS_MANDATORY?answer=NO"

    const val USER_CHOSEN_CATEGORY = "USER_CHOSEN_CATEGORY"
    const val USER_CHOSEN_CATEGORY_WITH_ID = "USER_CHOSEN_CATEGORY?categoryId="

    const val STATISTIC = "STATISTIC"
    const val STATISTIC_CHOSEN = "STATISTIC_CHOSEN"
    const val STATISTIC_CHOSEN_FOR_DAY = "STATISTIC_CHOSEN?answer=DAY"
    const val STATISTIC_CHOSEN_FOR_WEEK = "STATISTIC_CHOSEN?answer=WEEK"
    const val STATISTIC_CHOSEN_FOR_MONTH = "STATISTIC_CHOSEN?answer=MONTH"
    const val STATISTIC_CHOSEN_FOR_YEAR = "STATISTIC_CHOSEN?answer=YEAR"
    const val STATISTIC_CHOSEN_SELECT_PERIOD = "STATISTIC_CHOSEN?answer=SELECT_PERIOD"
}